version: '3.8'

services:
  app:
    image: node:20.10.0
    container_name: currency-today
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./application:/app
    command: bash -c
      " npm install
      && npm run dev"